Only send payment tenders to Forter that have transactions
workarea-commerce/workarea-forter pull request #10
Opened 2020-01-02 16:28 UTC by jyucis

Errors we being thrown when Forter was attempting to build transaction data for tenders that do not have any associated transaction. This commit also removes some extraneous code. 

FORTER-1

2020-01-02 16:29 UTC, jyucis commented on app/services/workarea/forter/payment.rb
> -        def credit_used
Credit_used and CC_month are extraneous code that Im removing.

2020-01-03 14:12 UTC, bencrouse requested changes
Can we get a unit test on this @jyucis ?

2020-01-03 14:14 UTC, bencrouse commented
Builds are probably failing because this is pointing at `workarea/master` which is Rails 6 now. I updated `master` on this plugin yesterday to point at `v3.5-stable`, so prob want to do this in this PR too to get a build running.

2020-01-06 19:23 UTC, bencrouse approved these changes

2020-01-06 19:23 UTC, merged