Set default Forter API version to 2.3
workarea-commerce/workarea-forter pull request #7
Opened 2019-10-09 17:27 UTC by jyucis

API version 2.3 allows for the general payment option, which
allows users to pass payment types that are not explicitly supported
by Forter.

2019-10-09 17:57 UTC, tubbo commented
i think you might need a v3.4-stable git dependency in Gemfile to get the tests passing https://github.com/workarea-commerce/workarea-forter/blob/master/Gemfile#L6

2019-10-09 17:58 UTC, tubbo requested changes
i think you might need a v3.4-stable git dependency in Gemfile to get the tests passing https://github.com/workarea-commerce/workarea-forter/blob/master/Gemfile#L6

2019-10-10 13:01 UTC, bencrouse requested changes
I guess this annotations is some new GitHub Actions thing, but anyways let's get the builds passing. Can you update the Gemfile to point at `v3.4-stable`?

2019-10-10 14:26 UTC, tubbo approved these changes

2019-10-11 13:33 UTC, bencrouse approved these changes

2019-10-11 13:34 UTC, merged